Implementating fem for verifying joint method in a truss (not enough values given)


In [1]:
import math
import numpy as np
import copy

In [2]:
#import classes for nodes and elements
from node import node
from ele import ele

In [3]:
help(node)

Help on class node in module node:

class node(builtins.object)
 |  node(num, pos_x, pos_y, dis_x, dis_y, f_x, f_y)
 |  
 |  Methods defined here:
 |  
 |  __init__(self, num, pos_x, pos_y, dis_x, dis_y, f_x, f_y)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  print(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



In [4]:
#define nodes along with boundary conditions
node1 = node(1,0,0,0,0,np.nan,np.nan)
node2 = node(2,0,0,np.nan,np.nan,np.nan,np.nan)
node3 = node(3,0,0,np.nan,np.nan,np.nan,np.nan)
node4 = node(4,0,0,np.nan,0,np.nan,np.nan)
node5 = node(5,0,0,np.nan,np.nan,np.nan,np.nan)
node6 = node(6,0,0,np.nan,np.nan,np.nan,-60)
node7 = node(7,0,0,np.nan,np.nan,np.nan,np.nan)



In [5]:
node1.print()
node2.print()
node3.print()
node4.print()
node5.print()
node6.print()
node7.print()

num =  1 
 pos_x = 0 
 pos_y =  0 
 dis_x =  0 
 dis_y =  0 
 f_x =  nan 
 f_y =  nan
num =  2 
 pos_x = 0 
 pos_y =  0 
 dis_x =  nan 
 dis_y =  nan 
 f_x =  nan 
 f_y =  nan
num =  3 
 pos_x = 0 
 pos_y =  0 
 dis_x =  nan 
 dis_y =  nan 
 f_x =  nan 
 f_y =  nan
num =  4 
 pos_x = 0 
 pos_y =  0 
 dis_x =  nan 
 dis_y =  0 
 f_x =  nan 
 f_y =  nan
num =  5 
 pos_x = 0 
 pos_y =  0 
 dis_x =  nan 
 dis_y =  nan 
 f_x =  nan 
 f_y =  nan
num =  6 
 pos_x = 0 
 pos_y =  0 
 dis_x =  nan 
 dis_y =  nan 
 f_x =  nan 
 f_y =  -60
num =  7 
 pos_x = 0 
 pos_y =  0 
 dis_x =  nan 
 dis_y =  nan 
 f_x =  nan 
 f_y =  nan


0

In [6]:
help(ele)


Help on class ele in module ele:

class ele(builtins.object)
 |  ele(num, length, area, ym, theta, node_a, node_b)
 |  
 |  Methods defined here:
 |  
 |  __init__(self, num, length, area, ym, theta, node_a, node_b)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  print(self)
 |  
 |  stiff(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



In [7]:
#define elements

ele1 = ele(1,2,1, 1 , math.pi/3, 1 , 2)
ele2 = ele(2,2,1, 1 , 0, 2 , 3)
ele3 = ele(3,2,1, 1, 2*math.pi / 3, 4, 3)
ele4 = ele(4,1,1, 1, 0, 5, 4)
ele5 = ele(5, 1, 1,1 ,0, 6, 5)
ele6 = ele(6, 1, 1, 1, 0, 7, 6)
ele7 = ele(7, 1,1,1, 0, 1, 7)
ele8 = ele(8, math.sqrt(3),1,1,math.pi/2, 7, 2)
ele9 = ele(9, 2, 1, 1, 2*math.pi/3, 6, 2)
ele10 =  ele(10, 2,1, 1, math.pi/3, 6, 3)
ele11 = ele(11, math.sqrt(3),1,1, math.pi/2,4, 3)

In [8]:
ele1.print()
ele2.print()
ele3.print()
ele4.print()
ele5.print()
ele6.print()
ele7.print()
ele8.print()
ele9.print()
ele10.print()
ele11.print()

num =  1 
 length= 2 
 area =  1 
 youngs modulus =  1 
 theta =  1.0471975511965976 
 node_a =  1 
 node_b =  2
num =  2 
 length= 2 
 area =  1 
 youngs modulus =  1 
 theta =  0 
 node_a =  2 
 node_b =  3
num =  3 
 length= 2 
 area =  1 
 youngs modulus =  1 
 theta =  2.0943951023931953 
 node_a =  4 
 node_b =  3
num =  4 
 length= 1 
 area =  1 
 youngs modulus =  1 
 theta =  0 
 node_a =  5 
 node_b =  4
num =  5 
 length= 1 
 area =  1 
 youngs modulus =  1 
 theta =  0 
 node_a =  6 
 node_b =  5
num =  6 
 length= 1 
 area =  1 
 youngs modulus =  1 
 theta =  0 
 node_a =  7 
 node_b =  6
num =  7 
 length= 1 
 area =  1 
 youngs modulus =  1 
 theta =  0 
 node_a =  1 
 node_b =  7
num =  8 
 length= 1.7320508075688772 
 area =  1 
 youngs modulus =  1 
 theta =  1.5707963267948966 
 node_a =  7 
 node_b =  2
num =  9 
 length= 2 
 area =  1 
 youngs modulus =  1 
 theta =  2.0943951023931953 
 node_a =  6 
 node_b =  2
num =  10 
 length= 2 
 area =  1 
 youngs modulus 

0

In [9]:
#generating stiffness matrix for all elements

print(ele1.stiff())
print(ele2.stiff())
print(ele3.stiff())
print(ele4.stiff())
print(ele5.stiff())
print(ele6.stiff())
print(ele7.stiff())
print(ele8.stiff())
print(ele9.stiff())
print(ele10.stiff())
print(ele11.stiff())


[[ 0.125       0.21650635 -0.125      -0.21650635]
 [ 0.21650635  0.375      -0.21650635 -0.375     ]
 [-0.125      -0.21650635  0.125       0.21650635]
 [-0.21650635 -0.375       0.21650635  0.375     ]]
[[ 0.5  0.  -0.5 -0. ]
 [ 0.   0.  -0.  -0. ]
 [-0.5 -0.   0.5  0. ]
 [-0.  -0.   0.   0. ]]
[[ 0.125      -0.21650635 -0.125       0.21650635]
 [-0.21650635  0.375       0.21650635 -0.375     ]
 [-0.125       0.21650635  0.125      -0.21650635]
 [ 0.21650635 -0.375      -0.21650635  0.375     ]]
[[ 1.  0. -1. -0.]
 [ 0.  0. -0. -0.]
 [-1. -0.  1.  0.]
 [-0. -0.  0.  0.]]
[[ 1.  0. -1. -0.]
 [ 0.  0. -0. -0.]
 [-1. -0.  1.  0.]
 [-0. -0.  0.  0.]]
[[ 1.  0. -1. -0.]
 [ 0.  0. -0. -0.]
 [-1. -0.  1.  0.]
 [-0. -0.  0.  0.]]
[[ 1.  0. -1. -0.]
 [ 0.  0. -0. -0.]
 [-1. -0.  1.  0.]
 [-0. -0.  0.  0.]]
[[ 2.16471679e-33  3.53525080e-17 -2.16471679e-33 -3.53525080e-17]
 [ 3.53525080e-17  5.77350269e-01 -3.53525080e-17 -5.77350269e-01]
 [-2.16471679e-33 -3.53525080e-17  2.16471679e-33  3.53

In [10]:
#list of nodes and elements
nodes = [node1 , node2 , node3  ,node4, node5, node6, node7]
eles = [ele1 , ele2 ,ele3, ele4, ele5, ele6, ele7, ele8, ele9, ele10, ele11]


In [11]:
#generate global stiffness matrix 

def globalstiff(eles , num_nodes):
    #dimension of global matrix
    dim = 2 * num_nodes
    #generate and store the element-wise stiffness matrices
    SMs = [e.stiff() for e in eles]
    
    GK = np.zeros((dim,dim))
    for i in range(1,dim+1):
        for j in range(1,dim + 1):
            for k in range(0 , num_nodes):
                e = eles[k]
                if e.node_a == math.ceil(i/2):
                    if e.node_a == math.ceil(j/2):
                        GK[i-1][j-1] += SMs[k][(i+1)%2][(j+1)%2]
                    if e.node_b == math.ceil(j/2):
                        GK[i-1][j-1] += SMs[k][i%2][2+(j+1)%2]
                if e.node_b == math.ceil(i/2):
                    if e.node_a == math.ceil(j/2):
                        GK[i-1][j-1] += SMs[k][2+(i+1)%2][j%2]
                    if e.node_b == math.ceil(j/2):
                        GK[i-1][j-1] += SMs[k][2+(i+1)%2][2+(j+1)%2]
    return GK
            
    

In [12]:
GK = globalstiff(eles , len(nodes))
GK

array([[ 1.125     ,  0.21650635, -0.21650635, -0.375     ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.21650635,  0.375     , -0.125     , -0.21650635,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        , -1.        ,  0.        ],
       [-0.21650635, -0.125     ,  0.625     ,  0.21650635,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [-0.375     , -0.21650635,  0.21650635,  0.375     , -0.5       ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.5       ,  0.625     ,
        -0.21650635,  0.21650635, -0.125     ,  0.        ,  0.        ,
         0.        ,  0.  

In [13]:
#create vector for node_dis and external_forces

dis_list = []
for n in nodes:
    dis_list.append(n.dis_x)
    dis_list.append(n.dis_y)
    
dis = np.array(dis_list)
print(dis)

f_list = []
for n in nodes:
    f_list.append(n.f_x)
    f_list.append(n.f_y)
    
f = np.array(f_list)
print(f)


[ 0.  0. nan nan nan nan nan  0. nan nan nan nan nan nan]
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan -60.  nan  nan]


In [14]:
#check for undetermined values in force and create linear eqns

GK_dis =  copy.deepcopy(GK)
f_dis =  copy.deepcopy(f)

del_row = []
index_list = list(range(0,2*len(nodes)))
for i in range(0,2*len(nodes)):
    if dis_list[i] == 0:
        del_row.append(i)
        index_list.remove(i)
        
print(del_row)
print(index_list)
        
GK_dis = np.delete(GK_dis,del_row,0)
GK_dis = np.delete(GK_dis,del_row,1)
f_dis = np.delete(f_dis,del_row,0)
    
print(GK_dis)
print(f_dis)


[0, 1, 7]
[2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13]
[[ 0.625       0.21650635  0.          0.          0.          0.
   0.          0.          0.          0.          0.        ]
 [ 0.21650635  0.375      -0.5         0.          0.          0.
   0.          0.          0.          0.          0.        ]
 [ 0.         -0.5         0.625      -0.21650635  0.21650635  0.
   0.          0.          0.          0.          0.        ]
 [ 0.          0.         -0.21650635  0.375      -0.375       0.
   0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.21650635 -0.375       1.125       0.
  -1.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          2.
   0.          0.         -1.          0.          0.        ]
 [ 0.          0.          0.          0.         -1.          0.
   0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        

In [15]:
ans_dis = np.linalg.solve(GK_dis , f_dis)
ans_dis

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [16]:
for i in range(0 , len(ans_dis)):
    dis[index_list[i]] = ans_dis[i]
dis

array([ 0.,  0., nan, nan, nan, nan, nan,  0., nan, nan, nan, nan, nan,
       nan])

In [17]:
ans_force = np.dot(GK,dis)
ans_force

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan])