In [13]:
import math
import numpy as np

$$ \begin{bmatrix}
2 & 3 & 5\\
7 & 8 & 9\\
5 & 6 & 7
\end{bmatrix}
\begin{bmatrix}
x\\
y\\
z 
\end{bmatrix}
=
\begin{bmatrix}
6\\
4\\
8
\end{bmatrix}
$$

The solution is $[-28 , 34 , -8]$

so let $z = -8$

The eqn then becomes

$$ \begin{bmatrix}
2 & 3 & 5\\
7 & 8 & 9\\
5 & 6 & 7
\end{bmatrix}
\begin{bmatrix}
x\\
y\\
-8 
\end{bmatrix}
=
\begin{bmatrix}
6\\
4\\
P
\end{bmatrix}
$$


In [14]:
#check for undetermined values in dis and create linear eqns

GK_dis =  np.array([[2 , 3, 5],[7 , 8 , 9],[5 , 6 , 7]])
dis_list = np.array([np.nan , np.nan , -8])
f_dis =  np.array([6 , 4 , 8])

#get a list of rows to remove
del_row = []

index_list = list(range(0,3))
for i in range(0,3):
    if not np.isnan(dis_list[i]):
        del_row.append(i)
        index_list.remove(i)

#remove the rows that have displacement given
GK_dis = np.delete(GK_dis,del_row,0)
f_dis = np.delete(f_dis,del_row,0)

#before deleting the columns we subratct these from force vector
for i in del_row:
    f_dis = f_dis - dis_list[i] * GK_dis[:,i]
    
#delete the columns that are due to the displacements that are determined
GK_dis = np.delete(GK_dis,del_row,1)

print(GK_dis)
print(dis_list)
print(f_dis)

[[2 3]
 [7 8]]
[nan nan -8.]
[46. 76.]


In [15]:
ans_dis = np.linalg.solve(GK_dis , f_dis)
ans_dis

array([-28.,  34.])

In [10]:
for i in range(0 , len(ans_dis)):
    dis[index_list[i]] = ans_dis[i]
dis

array([-28.,  34.,  -8.])

In [12]:
GK =  np.array([[2 , 3, 5],[7 , 8 , 9],[5 , 6 , 7]])
ans_force = np.dot(GK,dis)
ans_force

array([6., 4., 8.])