Implementating fem for truss using class

In [1]:
import math
import numpy as np
import copy

In [2]:
#import classes for nodes and elements
from node import node
from ele import ele

In [3]:
help(node)

Help on class node in module node:

class node(builtins.object)
 |  node(num, pos_x, pos_y, dis_x, dis_y, f_x, f_y)
 |  
 |  Methods defined here:
 |  
 |  __init__(self, num, pos_x, pos_y, dis_x, dis_y, f_x, f_y)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  print(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



In [4]:
#define nodes along with boundary conditions
node1 = node(1,0,0,0,0,0,0)
node2 = node(2,2,0,0,0,0,0)
node3 = node(3,4,0,0,0,0,0)
node4 = node(4,6,0,0,0,0,0)
node5 = node(5,8,0,0,0,0,0)
node6 = node(6,8,2.918,np.nan,np.nan,2,-1)
node7 = node(7,6,2.1838,np.nan,np.nan,0,-1)
node8 = node(8,4,1.4559,np.nan,np.nan,0,-1)
node9 = node(9,2,0.7279,np.nan,np.nan,0,-1)

In [5]:
node1.print()
node2.print()
node3.print()
node4.print()
node5.print()
node6.print()
node7.print()
node8.print()
node9.print()

num =  1 
 pos_x = 0 
 pos_y =  0 
 dis_x =  0 
 dis_y =  0 
 f_x =  0 
 f_y =  0
num =  2 
 pos_x = 2 
 pos_y =  0 
 dis_x =  0 
 dis_y =  0 
 f_x =  0 
 f_y =  0
num =  3 
 pos_x = 4 
 pos_y =  0 
 dis_x =  0 
 dis_y =  0 
 f_x =  0 
 f_y =  0
num =  4 
 pos_x = 6 
 pos_y =  0 
 dis_x =  0 
 dis_y =  0 
 f_x =  0 
 f_y =  0
num =  5 
 pos_x = 8 
 pos_y =  0 
 dis_x =  0 
 dis_y =  0 
 f_x =  0 
 f_y =  0
num =  6 
 pos_x = 8 
 pos_y =  2.918 
 dis_x =  nan 
 dis_y =  nan 
 f_x =  2 
 f_y =  -1
num =  7 
 pos_x = 6 
 pos_y =  2.1838 
 dis_x =  nan 
 dis_y =  nan 
 f_x =  0 
 f_y =  -1
num =  8 
 pos_x = 4 
 pos_y =  1.4559 
 dis_x =  nan 
 dis_y =  nan 
 f_x =  0 
 f_y =  -1
num =  9 
 pos_x = 2 
 pos_y =  0.7279 
 dis_x =  nan 
 dis_y =  nan 
 f_x =  0 
 f_y =  -1


0

In [6]:
help(ele)

Help on class ele in module ele:

class ele(builtins.object)
 |  ele(num, length, area, ym, theta, node_a, node_b)
 |  
 |  Methods defined here:
 |  
 |  __init__(self, num, length, area, ym, theta, node_a, node_b)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  print(self)
 |  
 |  stiff(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



In [7]:
#define elements

ele1 = ele(1,2.0000,1,1, 0 , node1 , node2)
ele2 = ele(2,2.0000,1, 1 , 0, node2 , node3)
ele3 = ele(3,2.000,1, 1 , 0, node3 , node4)
ele4 = ele(4,2.0000,1, 1 , 0 , node4 , node5)
ele5 = ele(5,2.9118,1, 1 , math.pi / 2 , node5 , node6)
ele6 = ele(6,2.1284,1,1, math.pi / 9, node7 , node6)
ele7 = ele(7,2.1284,1, 1 , math.pi / 9 , node8 , node7)
ele8 = ele(8,2.1284,1, 1 , math.pi / 9 , node9 , node8)
ele9 = ele(9,2.1284,1, 1 , math.pi / 9 , node1 , node9)
ele10 = ele(10,0.7279,1, 1 , math.pi / 2, node2 , node9)
ele11 = ele(11,2.4738,1, 1 , math.pi / 5 , node2 , node8)
ele12 = ele(12,1.4559,1,1, math.pi / 2, node3 , node8)
ele13 = ele(13,2.4738,1, 1 , 4*math.pi / 5 , node4 , node8)
ele14 = ele(14,2.1838,1, 1 , math.pi / 2 , node4 , node7)
ele15 = ele(15,3.5325,1, 1 , 14*math.pi / 45 , node4, node6)



In [8]:
ele1.print()
ele2.print()
ele3.print()
ele4.print()
ele5.print()
ele6.print()
ele7.print()
ele8.print()
ele9.print()
ele10.print()
ele11.print()
ele12.print()
ele13.print()
ele14.print()
ele15.print()

num =  1 
 length= 2.0 
 area =  1 
 youngs modulus =  1 
 theta =  0 
 node_a =  <node.node object at 0x7f7a8d434370> 
 node_b =  <node.node object at 0x7f7a8d434310>
num =  2 
 length= 2.0 
 area =  1 
 youngs modulus =  1 
 theta =  0 
 node_a =  <node.node object at 0x7f7a8d434310> 
 node_b =  <node.node object at 0x7f7a8d4343a0>
num =  3 
 length= 2.0 
 area =  1 
 youngs modulus =  1 
 theta =  0 
 node_a =  <node.node object at 0x7f7a8d4343a0> 
 node_b =  <node.node object at 0x7f7a8d434340>
num =  4 
 length= 2.0 
 area =  1 
 youngs modulus =  1 
 theta =  0 
 node_a =  <node.node object at 0x7f7a8d434340> 
 node_b =  <node.node object at 0x7f7a8d4343d0>
num =  5 
 length= 2.9118 
 area =  1 
 youngs modulus =  1 
 theta =  1.5707963267948966 
 node_a =  <node.node object at 0x7f7a8d4343d0> 
 node_b =  <node.node object at 0x7f7a8d434400>
num =  6 
 length= 2.1284 
 area =  1 
 youngs modulus =  1 
 theta =  0.3490658503988659 
 node_a =  <node.node object at 0x7f7a8d434430> 


0

In [9]:
#generating stiffness matrix for all elements

print(ele1.stiff())
print(ele2.stiff())
print(ele3.stiff())


[[ 0.5  0.  -0.5 -0. ]
 [ 0.   0.  -0.  -0. ]
 [-0.5 -0.   0.5  0. ]
 [-0.  -0.   0.   0. ]]
[[ 0.5  0.  -0.5 -0. ]
 [ 0.   0.  -0.  -0. ]
 [-0.5 -0.   0.5  0. ]
 [-0.  -0.   0.   0. ]]
[[ 0.5  0.  -0.5 -0. ]
 [ 0.   0.  -0.  -0. ]
 [-0.5 -0.   0.5  0. ]
 [-0.  -0.   0.   0. ]]


In [10]:
#list of nodes and elements
nodes = [node1 , node2 , node3,node4,node5,node6,node7,node8,node9]
eles = [ele1 , ele2 ,ele3,ele4,ele5,ele6,ele7,ele8,ele9,ele10,ele11,ele12,ele13,ele14,ele15]


In [11]:
#generate global stiffness matrix 

def globalstiff(eles , num_nodes):
    #dimension of global matrix
    dim = 2 * num_nodes
    #generate and store the element-wise stiffness matrices
    SMs = [e.stiff() for e in eles]
    
    GK = np.zeros((dim,dim))
    
    for e in eles:
        i = 2 * e.node_a.num -2
        j = 2 * e.node_a.num -1
        k = 2 * e.node_b.num -2
        l = 2 * e.node_b.num -1
        e_stiff = e.stiff()
        
        index = [i,j,k,l]
        index2d = [(a,b) for a in index for b in index]
        d = {i:0, j:1, k:2, l:3}
        for p,q in index2d:
            GK[p][q] = GK[p][q] + e_stiff[d[p]][d[q]]
            
    return GK
            
    

In [12]:
GK = globalstiff(eles , 9)
GK

array([[ 9.14876067e-01,  1.51002539e-01, -5.00000000e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -4.14876067e-01, -1.51002539e-01],
       [ 1.51002539e-01,  5.49604296e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -1.51002539e-01, -5.49604296e-02],
       [-5.00000000e-01,  0.00000000e+00,  1.26457616e+00,
         1.92225830e-01, -5.00000000e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -2.64576157e

In [13]:
#create vector for node_dis and external_forces 

dis_list = []
for n in nodes:
    dis_list.append(n.dis_x)
    dis_list.append(n.dis_y)
    
dis = np.array(dis_list)
print(dis)

f_list = []
for n in nodes:
    f_list.append(n.f_x)
    f_list.append(n.f_y)
    
f = np.array(f_list)
print(f)


[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. nan nan nan nan nan nan nan nan]
[ 0  0  0  0  0  0  0  0  0  0  2 -1  0 -1  0 -1  0 -1]


In [14]:
#check for undetermined values in dis and create linear eqns

GK_dis =  copy.deepcopy(GK)
f_dis =  copy.deepcopy(f)

del_row = []
index_list = list(range(0,2*len(nodes)))
for i in range(0,2*len(nodes)):
    if dis_list[i] == 0:
        del_row.append(i)
        index_list.remove(i)
GK_dis = np.delete(GK_dis,del_row,0)
GK_dis = np.delete(GK_dis,del_row,1)
f_dis = np.delete(f_dis,del_row,0)
    
print(GK_dis)
print(f_dis)
print(index_list)
        
    
        

[[ 0.50339601  0.28223875 -0.41487607 -0.15100254  0.          0.
   0.          0.        ]
 [ 0.28223875  0.5929563  -0.15100254 -0.05496043  0.          0.
   0.          0.        ]
 [-0.41487607 -0.15100254  0.82975213  0.30200508 -0.41487607 -0.15100254
   0.          0.        ]
 [-0.15100254 -0.05496043  0.30200508  0.56783825 -0.15100254 -0.05496043
   0.          0.        ]
 [ 0.          0.         -0.41487607 -0.15100254  1.35890445  0.30200508
  -0.41487607 -0.15100254]
 [ 0.          0.         -0.15100254 -0.05496043  0.30200508  1.0761017
  -0.15100254 -0.05496043]
 [ 0.          0.          0.          0.         -0.41487607 -0.15100254
   0.82975213  0.30200508]
 [ 0.          0.          0.          0.         -0.15100254 -0.05496043
   0.30200508  1.48373594]]
[ 2 -1  0 -1  0 -1  0 -1]
[10, 11, 12, 13, 14, 15, 16, 17]


In [15]:
#check for undetermined values in force and create linear eqns

GK_dis =  copy.deepcopy(GK)
f_dis =  copy.deepcopy(f)

del_row = []
index_list = list(range(0,2*len(nodes)))
for i in range(0,2*len(nodes)):
    if dis_list[i] == 0:
        del_row.append(i)
        index_list.remove(i)
GK_dis = np.delete(GK_dis,del_row,0)
GK_dis = np.delete(GK_dis,del_row,1)
f_dis = np.delete(f_dis,del_row,0)
    
print(GK_dis)
print(f_dis)

[[ 0.50339601  0.28223875 -0.41487607 -0.15100254  0.          0.
   0.          0.        ]
 [ 0.28223875  0.5929563  -0.15100254 -0.05496043  0.          0.
   0.          0.        ]
 [-0.41487607 -0.15100254  0.82975213  0.30200508 -0.41487607 -0.15100254
   0.          0.        ]
 [-0.15100254 -0.05496043  0.30200508  0.56783825 -0.15100254 -0.05496043
   0.          0.        ]
 [ 0.          0.         -0.41487607 -0.15100254  1.35890445  0.30200508
  -0.41487607 -0.15100254]
 [ 0.          0.         -0.15100254 -0.05496043  0.30200508  1.0761017
  -0.15100254 -0.05496043]
 [ 0.          0.          0.          0.         -0.41487607 -0.15100254
   0.82975213  0.30200508]
 [ 0.          0.          0.          0.         -0.15100254 -0.05496043
   0.30200508  1.48373594]]
[ 2 -1  0 -1  0 -1  0 -1]


In [16]:
ans_dis = np.linalg.solve(GK_dis , f_dis)
ans_dis

array([12.48407187, -6.04631381,  7.00856832, -2.1838    ,  2.35025907,
       -0.56650909,  1.33696724, -0.7279    ])

In [17]:
for i in range(0 , len(ans_dis)):
    dis[index_list[i]] = ans_dis[i]
dis

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
       12.48407187, -6.04631381,  7.00856832, -2.1838    ,  2.35025907,
       -0.56650909,  1.33696724, -0.7279    ])

In [18]:
ans_force = np.dot(GK,dis)
ans_force

array([-4.44760964e-01, -1.61879752e-01, -5.12924832e-01,  6.27338296e-01,
        2.38262773e-17,  3.89112638e-01, -1.04231420e+00,  1.06894218e+00,
        1.27148136e-16,  2.07648664e+00,  2.00000000e+00, -1.00000000e+00,
        6.66133815e-16, -1.00000000e+00,  4.99600361e-16, -1.00000000e+00,
       -3.33066907e-16, -1.00000000e+00])