Implementating fem for verifying joint method in a truss (adding values)



![](joint2ndexample.jpg)

In [38]:
import math
import numpy as np
import copy

In [39]:
#import classes for nodes and elements
from node import node
from ele import ele

In [40]:
help(node)

Help on class node in module node:

class node(builtins.object)
 |  node(num, pos_x, pos_y, dis_x, dis_y, f_x, f_y)
 |  
 |  Methods defined here:
 |  
 |  __init__(self, num, pos_x, pos_y, dis_x, dis_y, f_x, f_y)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  print(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



In [41]:
#define nodes along with boundary conditions
node1 = node(1,0,0,0,0,10,45.185)
node2 = node(2,0,0,np.nan,np.nan,0,-50)
node3 = node(3,0,0,np.nan,np.nan,0,104.815)
node4 = node(4,0,0,np.nan,np.nan,-10,-50)
node5 = node(5,0,0,np.nan,np.nan,0,-50)


In [42]:
node1.print()
node2.print()
node3.print()
node4.print()
node5.print()


num =  1 
 pos_x = 0 
 pos_y =  0 
 dis_x =  0 
 dis_y =  0 
 f_x =  10 
 f_y =  45.185
num =  2 
 pos_x = 0 
 pos_y =  0 
 dis_x =  nan 
 dis_y =  nan 
 f_x =  0 
 f_y =  -50
num =  3 
 pos_x = 0 
 pos_y =  0 
 dis_x =  nan 
 dis_y =  nan 
 f_x =  0 
 f_y =  104.815
num =  4 
 pos_x = 0 
 pos_y =  0 
 dis_x =  nan 
 dis_y =  nan 
 f_x =  -10 
 f_y =  -50
num =  5 
 pos_x = 0 
 pos_y =  0 
 dis_x =  nan 
 dis_y =  nan 
 f_x =  0 
 f_y =  -50


0

In [43]:
help(ele)


Help on class ele in module ele:

class ele(builtins.object)
 |  ele(num, length, area, ym, theta, node_a, node_b)
 |  
 |  Methods defined here:
 |  
 |  __init__(self, num, length, area, ym, theta, node_a, node_b)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  print(self)
 |  
 |  stiff(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



In [44]:
#define elements

ele1 = ele(1,2,1, 1 , 0, 1 , 2)
ele2 = ele(2,2,1, 1 , 0, 2 , 3)
ele3 = ele(3,1.4559,1, 1, math.pi / 2, 4, 3)
ele4 = ele(4,2.1284,1, 1, 11*math.pi/18, 5, 4)
ele5 = ele(5, 2.1284, 1,1 ,math.pi/9, 6, 5)
ele6 = ele(6, 0.7280, 1, 1, math.pi/2, 5, 2)
ele7 = ele(7, 2.4738,1,1, 36.05*math.pi/180, 4, 2)


In [45]:
ele1.print()
ele2.print()
ele3.print()
ele4.print()
ele5.print()
ele6.print()
ele7.print()


num =  1 
 length= 2 
 area =  1 
 youngs modulus =  1 
 theta =  0 
 node_a =  1 
 node_b =  2
num =  2 
 length= 2 
 area =  1 
 youngs modulus =  1 
 theta =  0 
 node_a =  2 
 node_b =  3
num =  3 
 length= 1.4559 
 area =  1 
 youngs modulus =  1 
 theta =  1.5707963267948966 
 node_a =  4 
 node_b =  3
num =  4 
 length= 2.1284 
 area =  1 
 youngs modulus =  1 
 theta =  1.9198621771937623 
 node_a =  5 
 node_b =  4
num =  5 
 length= 2.1284 
 area =  1 
 youngs modulus =  1 
 theta =  0.3490658503988659 
 node_a =  6 
 node_b =  5
num =  6 
 length= 0.728 
 area =  1 
 youngs modulus =  1 
 theta =  1.5707963267948966 
 node_a =  5 
 node_b =  2
num =  7 
 length= 2.4738 
 area =  1 
 youngs modulus =  1 
 theta =  0.6291911953439557 
 node_a =  4 
 node_b =  2


0

In [46]:
#generating stiffness matrix for all elements

print(ele1.stiff())
print(ele2.stiff())
print(ele3.stiff())
print(ele4.stiff())
print(ele5.stiff())
print(ele6.stiff())
print(ele7.stiff())



[[ 0.5  0.  -0.5 -0. ]
 [ 0.   0.  -0.  -0. ]
 [-0.5 -0.   0.5  0. ]
 [-0.  -0.   0.   0. ]]
[[ 0.5  0.  -0.5 -0. ]
 [ 0.   0.  -0.  -0. ]
 [-0.5 -0.   0.5  0. ]
 [-0.  -0.   0.   0. ]]
[[ 2.57531387e-33  4.20580671e-17 -2.57531387e-33 -4.20580671e-17]
 [ 4.20580671e-17  6.86860361e-01 -4.20580671e-17 -6.86860361e-01]
 [-2.57531387e-33 -4.20580671e-17  2.57531387e-33  4.20580671e-17]
 [-4.20580671e-17 -6.86860361e-01  4.20580671e-17  6.86860361e-01]]
[[ 0.05496043 -0.15100254 -0.05496043  0.15100254]
 [-0.15100254  0.41487607  0.15100254 -0.41487607]
 [-0.05496043  0.15100254  0.05496043 -0.15100254]
 [ 0.15100254 -0.41487607 -0.15100254  0.41487607]]
[[ 0.41487607  0.15100254 -0.41487607 -0.15100254]
 [ 0.15100254  0.05496043 -0.15100254 -0.05496043]
 [-0.41487607 -0.15100254  0.41487607  0.15100254]
 [-0.15100254 -0.05496043  0.15100254  0.05496043]]
[[ 5.15027398e-33  8.41103571e-17 -5.15027398e-33 -8.41103571e-17]
 [ 8.41103571e-17  1.37362637e+00 -8.41103571e-17 -1.37362637e+00]
 

In [47]:
#list of nodes and elements
nodes = [node1 , node2 , node3  ,node4, node5]
eles = [ele1 , ele2 ,ele3, ele4, ele5, ele6, ele7]


In [48]:
#generate global stiffness matrix 

def globalstiff(eles , num_nodes):
    #dimension of global matrix
    dim = 2 * num_nodes
    #generate and store the element-wise stiffness matrices
    SMs = [e.stiff() for e in eles]
    
    GK = np.zeros((dim,dim))
    for i in range(1,dim+1):
        for j in range(1,dim + 1):
            for k in range(0 , num_nodes):
                e = eles[k]
                if e.node_a == math.ceil(i/2):
                    if e.node_a == math.ceil(j/2):
                        GK[i-1][j-1] += SMs[k][(i+1)%2][(j+1)%2]
                    if e.node_b == math.ceil(j/2):
                        GK[i-1][j-1] += SMs[k][i%2][2+(j+1)%2]
                if e.node_b == math.ceil(i/2):
                    if e.node_a == math.ceil(j/2):
                        GK[i-1][j-1] += SMs[k][2+(i+1)%2][j%2]
                    if e.node_b == math.ceil(j/2):
                        GK[i-1][j-1] += SMs[k][2+(i+1)%2][2+(j+1)%2]
    return GK
            
    

In [49]:
GK = globalstiff(eles , len(nodes))
GK

array([[ 5.00000000e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -5.00000000e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00, -5.00000000e-01,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -5.00000000e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -5.00000000e-01,  5.00000000e-01,  4.20580671e-17,
        -4.20580671e-17, -2.57531387e-33,  0.00000000e+00,
         0.

In [50]:
#create vector for node_dis and external_forces

dis_list = []
for n in nodes:
    dis_list.append(n.dis_x)
    dis_list.append(n.dis_y)
    
dis = np.array(dis_list)
print(dis)

f_list = []
for n in nodes:
    f_list.append(n.f_x)
    f_list.append(n.f_y)
    
f = np.array(f_list)
print(f)


[ 0.  0. nan nan nan nan nan nan nan nan]
[ 10.     45.185   0.    -50.      0.    104.815 -10.    -50.      0.
 -50.   ]


In [51]:
#check for undetermined values in force and create linear eqns

GK_dis =  copy.deepcopy(GK)
f_dis =  copy.deepcopy(f)

del_row = []
index_list = list(range(0,2*len(nodes)))
for i in range(0,2*len(nodes)):
    if dis_list[i] == 0:
        del_row.append(i)
        index_list.remove(i)
        
print(del_row)
print(index_list)
        
GK_dis = np.delete(GK_dis,del_row,0)
GK_dis = np.delete(GK_dis,del_row,1)
f_dis = np.delete(f_dis,del_row,0)
    
print(GK_dis)
print(f_dis)


[0, 1]
[2, 3, 4, 5, 6, 7, 8, 9]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -5.00000000e-01  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -5.00000000e-01  5.00000000e-01  4.20580671e-17
  -4.20580671e-17 -2.57531387e-33  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  4.20580671e-17  6.86860361e-01
  -6.86860361e-01 -4.20580671e-17  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -4.20580671e-17 -6.86860361e-01
   5.49604296e-02 -1.51002539e-01  1.51002539e-01 -5.49604296e-02]
 [ 0.00000000e+00  0.00000000e+00 -2.57531387e-33 -4.20580671e-17
  -1.51002539e-01  1.10173643e+00 -4.14876067e-01  1.51002539e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.51002539e-01 -4.14876067e-01  4.69836497e-01  1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  0.

In [52]:
ans_dis = np.linalg.solve(GK_dis , f_dis)
ans_dis

array([   0.        ,  100.        ,  100.        ,   23.07439738,
       -129.52576112,  -49.39913798,   -1.99175937, -105.69505888])

In [53]:
for i in range(0 , len(ans_dis)):
    dis[index_list[i]] = ans_dis[i]
dis

array([   0.        ,    0.        ,    0.        ,  100.        ,
        100.        ,   23.07439738, -129.52576112,  -49.39913798,
         -1.99175937, -105.69505888])

In [54]:
ans_force = np.dot(GK,dis)
ans_force

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -5.00000000e+01,
        0.00000000e+00,  1.04815000e+02, -1.00000000e+01, -5.00000000e+01,
        2.77555756e-15, -5.00000000e+01])