# Direct Stiffness Method


![](qn1.png)

### Determining nodal displacement of stepped bar, reaction support and stresses in each element.<br> [ E = 200 GPa]

#### 1. Discretization

![](disc.png)

#### Stiffness Matrix:

$$[K] = \frac{AE}{L} \begin{bmatrix} 1 & -1 \\ -1 & 1 \end{bmatrix}$$

We have,<br>
    $ A_1 = A_2 = 200 mm^2 $,<br>
    $ A_3 = 100 mm^2 $,<br>
    $ E = 200 GPa \hspace{0.5cm} or\hspace{0.5cm} 200 * 10^3 N/ (mm)^2 $,<br>
    $ L_1 = L_2 = 100 mm $,<br>
    $ L_3 = 150mm $

#### Now, <br>
$$[K_n] = \frac{A_nE}{L_n} \begin{bmatrix} 1 & -1 \\ -1 & 1 \end{bmatrix}$$

In [30]:
import math
import numpy as np

SM = np.array([[1,-1],[-1,1]])
A_1 = A_2 = 200
A_3 = 100
E = 200000
L_1 = L_2 = 100
L_3 = 150

K_1 = K_2 = ((A_1 * E)/L_1) * SM
K_3 = ((A_3 * E)/L_3) * SM

K_1, K_2, K_3

(array([[ 400000., -400000.],
        [-400000.,  400000.]]),
 array([[ 400000., -400000.],
        [-400000.,  400000.]]),
 array([[ 133333.33333333, -133333.33333333],
        [-133333.33333333,  133333.33333333]]))

#### As it is in 1-D, the degree of freedom for each node is only 1.<br><br>Thus the size of Global Stiffness Matrix :<br>
                No. of nodes * Degree of freedom = 4 X 1 = 4

In [31]:
GSM = np.array([[4, -4, 0, 0],[-1, 8, -4, 0], [0, -4, 5.33, -1.33], [0, 0, -1.33, 1.33]])* 100000
GSM

array([[ 400000., -400000.,       0.,       0.],
       [-100000.,  800000., -400000.,       0.],
       [      0., -400000.,  533000., -133000.],
       [      0.,       0., -133000.,  133000.]])

### Equillibrium Equation 

$$ [K] * [d] = [F] $$ <br>where K is Global Stiffness Matrix, d is 4 X 1 displacement vector for 4 nodes and F is also a 4 X 1 force vector of the nodes.<br>
    
Now here, Let $d_1,d_2,d_3$ and $d_4$ be elements of $d$ and $f_1,f_2,f_3$ and $f_4$ be elements of $f$. 

Here, $d_1 = 0$, since Node one is the support and is rigid and thus no displacement takes place. Also $f_1 = R$ which is the reaction force, $f_2 = 20 kN$, $f_3 = 0$ since the 3rd node is the change of cross section only and $f_4 = 10kN$.

$$ 10^5\begin{bmatrix} 4 & -4 & 0 & 0 \\ -4 & 8 & -4 & 0 \\ 0 & -4 & 5.33 & -1.33 \\ 0 & 0 & -1.33 & 1.33 \end{bmatrix} * \begin{bmatrix} 0 \\ d_2 \\ d_3 \\ d_4 \end{bmatrix} = \begin{bmatrix} R \\ 20000 \\ 0 \\ 10000 \end{bmatrix} $$

In [61]:
nGSM = GSM[1:,1:]                           # sliced GSM matrix
nf = np.array([[20000],[0],[10000]])        # sliced force vector
nd = np.dot(np.linalg.inv(nGSM),nf)         # matrix product 
d_1, d_2, d_3, d_4 = 0, nd[0,0],nd[1,0],nd[2,0]
d_1, d_2, d_3, d_4

(0, 0.07500000000000001, 0.1, 0.17518796992481203)

To find R:


In [45]:
R = (4 * d_1 -4 * d_2 + 0 * d_3 + 0 * d_4) * 100000
R

-30000.000000000004


#### Therefore : 
$$ R = -30 kN$$

Now we know,

 Stress ($\sigma$) $= E * [B] * [d]$ <br><br>
 where, $$B = \frac{1}{L_1} \begin{bmatrix} -1 & 1 \end{bmatrix} $$ 

In [59]:
bm = np.array([-1,1])
d = np.array([[d_1], [d_2], [d_3], [d_4]])

Sigma_1 = np.dot(E * (1/L_1) * bm , d[0:2])
Sigma_2 = np.dot(E * (1/L_2) * bm , d[1:3])
Sigma_3 = np.dot(E * (1/L_3) * bm , d[2:4])

sigma_1,sigma_2,sigma_3 = Sigma_1[0],Sigma_2[0],Sigma_3[0]
sigma_1, sigma_2, sigma_3

(150.00000000000003, 49.99999999999997, 100.25062656641606)