Implementating fem for truss using class

In [17]:
import math
import numpy as np

In [18]:
#import classes for nodes and elements
from node import node
from ele import ele

In [19]:
#define nodes
node1 = node(1,0,0,np.nan,np.nan,np.nan,np.nan)
node2 = node(2,2,0,np.nan,np.nan,np.nan,np.nan)
node3 = node(3,2,2,np.nan,np.nan,100000,-200000)

In [20]:
node1.print()
node2.print()
node3.print()

num =  1 
 pos_x = 0 
 pos_y =  0 
 dis_x =  nan 
 dis_y =  nan 
 f_x =  nan 
 f_y =  nan
num =  2 
 pos_x = 2 
 pos_y =  0 
 dis_x =  nan 
 dis_y =  nan 
 f_x =  nan 
 f_y =  nan
num =  3 
 pos_x = 2 
 pos_y =  2 
 dis_x =  nan 
 dis_y =  nan 
 f_x =  100000 
 f_y =  -200000


0

In [21]:
#define elements

ele1 = ele(1,1,0.01, 210 * 10**9 , 0 , 1 , 2)
ele2 = ele(2,1,0.01, 210 * 10**9 , math.pi / 2 , 2 , 3)
ele3 = ele(3,1*math.sqrt(2),0.01, 210 * 10**9 , math.pi / 4 , 1 , 3)


In [22]:
ele1.print()
ele2.print()
ele3.print()

num =  1 
 length= 1 
 area =  0.01 
 youngs modulus =  210000000000 
 theta =  0 
 node_a =  1 
 node_b =  2
num =  2 
 length= 1 
 area =  0.01 
 youngs modulus =  210000000000 
 theta =  1.5707963267948966 
 node_a =  2 
 node_b =  3
num =  3 
 length= 1.4142135623730951 
 area =  0.01 
 youngs modulus =  210000000000 
 theta =  0.7853981633974483 
 node_a =  1 
 node_b =  3


0

In [23]:
#generating stiffness matrix for all elements

print(ele1.stiff())
print(ele2.stiff())
print(ele3.stiff())


[[ 2.1e+09  0.0e+00 -2.1e+09 -0.0e+00]
 [ 0.0e+00  0.0e+00 -0.0e+00 -0.0e+00]
 [-2.1e+09 -0.0e+00  2.1e+09  0.0e+00]
 [-0.0e+00 -0.0e+00  0.0e+00  0.0e+00]]
[[ 7.87373886e-24  1.28587914e-07 -7.87373886e-24 -1.28587914e-07]
 [ 1.28587914e-07  2.10000000e+09 -1.28587914e-07 -2.10000000e+09]
 [-7.87373886e-24 -1.28587914e-07  7.87373886e-24  1.28587914e-07]
 [-1.28587914e-07 -2.10000000e+09  1.28587914e-07  2.10000000e+09]]
[[ 7.4246212e+08  7.4246212e+08 -7.4246212e+08 -7.4246212e+08]
 [ 7.4246212e+08  7.4246212e+08 -7.4246212e+08 -7.4246212e+08]
 [-7.4246212e+08 -7.4246212e+08  7.4246212e+08  7.4246212e+08]
 [-7.4246212e+08 -7.4246212e+08  7.4246212e+08  7.4246212e+08]]


In [ ]:
#list of nodes and elements
